#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/fb634ae8-e18f-436e-aab4-912ec53b2f87 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch toggle;
  int bLUE;
  int gREEN;
  int rED;
  bool status_check;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#define S0 16
#define S1 5
#define S2 4
#define S3 0
#define out 14
//int red=0,green=0,blue=0;

void setup() {
  pinMode(LED_BUILTIN,OUTPUT);
  pinMode(S0,OUTPUT);
  pinMode(S1,OUTPUT);
  pinMode(S2,OUTPUT);
  pinMode(S3,OUTPUT);
  pinMode(out,INPUT);
  digitalWrite(S0,HIGH);
  digitalWrite(S1,LOW);
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
   digitalWrite(LED_BUILTIN,HIGH);
  delay(100);
  digitalWrite(S2,LOW);
  digitalWrite(S3,LOW);
  rED=pulseIn(out,LOW);
  delay(100);
  digitalWrite(S2,HIGH);
  digitalWrite(S3,HIGH);
  gREEN=pulseIn(out,LOW);
  delay(100);
  digitalWrite(S2,LOW);
  digitalWrite(S3,HIGH);
  bLUE=pulseIn(out,LOW);
  delay(100); 
  /*Serial.print("RED= ");
  Serial.print(red);
  Serial.print("\tGREEN= ");
  Serial.print(green);
  Serial.print("\tBLUE= ");
  Serial.print(blue);
  Serial.print("\n"); */
  digitalWrite(LED_BUILTIN,LOW); 
  delay(100);
}







/*
  Since Toggle is READ_WRITE variable, onToggleChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onToggleChange()  {
  // Add your code here to act upon Toggle change
}





