// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6e1ab6e8-81aa-4560-811e-6fa2fc4bb680";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onToggleChange();

CloudSwitch toggle;
int bLUE;
int gREEN;
int rED;
bool status_check;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(toggle, READWRITE, ON_CHANGE, onToggleChange, 1);
  ArduinoCloud.addProperty(bLUE, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(gREEN, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(rED, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(status_check, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
